flashme/config/routes.rb
Flashme::Application.routes.draw do
  root to: "welcome#show", via: :get

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create]
  resources :decks do
    resources :cards, except: [:index]
  end
end

flashme/app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :back, :front
  belongs_to :deck
end

flashme/app/models/deck.rb
class Deck < ActiveRecord::Base
  attr_accessible :name
  has_many :cards
  # Deck.new(attributes)
  # Deck.create(attributes)
  # deck.update_attributes(attributes)
  #
  def self.current
    order("created_at DESC")
  end
end

flashme/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username
  has_many :decks
end

flashme/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def sign_in user
    cookies.signed[:user_id] = user.id
  end

  def require_login
    unless signed_in?
      redirect_to new_session_path
    end
  end

  def current_user
    if cookies[:user_id]
      @current_user ||= User.find_by_id(cookies.signed[:user_id])
    end
  end
  helper_method :current_user

  def signed_in?
    current_user
  end
  helper_method :signed_in?
end

flashme/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :require_login

  def show
    @deck = find_deck
    @card = find_card @deck
  end

  def new
    @deck = find_deck
    @card = @deck.cards.new
  end

  def create
    deck = find_deck
    card = deck.cards.new(params[:card])
    card.save
    redirect_to deck
  end

  def edit
    @deck = find_deck
    @card = find_card @deck
  end

  def update
    deck = find_deck
    card = find_card deck
    card.update_attributes(params[:card])
    redirect_to deck
  end

  def destroy
    deck = find_deck
    card = find_card deck
    card.destroy
    redirect_to deck
  end

  private

  def find_deck
    current_user.decks.find(params[:deck_id])
  end

  def find_card deck
    deck.cards.find(params[:id])
  end
end

flashme/app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :require_login

  def index
    @decks = decks.current
  end

  def new
    @deck = decks.new
  end

  def create
    deck = decks.new(params[:deck])
    deck.save
    redirect_to decks_path
  end

  def show
    @deck = decks.find(params[:id])
    @cards = @deck.cards
  end

  def edit
    @deck = decks.find(params[:id])
  end

  def update
    deck = decks.find(params[:id])
    deck.update_attributes(params[:deck])
    redirect_to decks_path
  end

  def destroy
    deck = decks.find(params[:id])
    deck.destroy
    redirect_to decks_path
  end

  private

  def decks
    current_user.decks
  end
end

flashme/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:session][:username])
    if user
      sign_in user
    end
    redirect_to decks_path
  end

  def destroy
    cookies.delete(:user_id)
    redirect_to root_path
  end
end

flashme/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(params[:user])
    user.save
    sign_in user
    redirect_to decks_path
  end
end

flashme/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

flashme/app/helpers/application_helper.rb
module ApplicationHelper
end

flashme/app/views/cards/edit.html.erb
<%= form_for([@deck, @card]) do |form| %>
  <div>
    <%= form.label :front %>
    <%= form.text_field :front %>
  </div>

  <div>
    <%= form.label :back %>
    <%= form.text_field :back %>
  </div>

  <%= form.submit "Update" %>
<% end %>

flashme/app/views/cards/new.html.erb
<%= form_for([@deck, @card]) do |form| %>
  <div>
    <%= form.label :front %>
    <%= form.text_field :front %>
  </div>

  <div>
    <%= form.label :back %>
    <%= form.text_field :back %>
  </div>

  <%= form.submit "Create" %>
<% end %>

flashme/app/views/cards/show.html.erb
<div>
  <%= @card.front %>
</div>
<div>
  <%= @card.back %>
</div>

<%= link_to @card.deck.name, @card.deck %>

flashme/app/views/decks/edit.html.erb
Update Deck
<%= form_for(@deck) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "Update deck" %>
<% end %>

flashme/app/views/decks/index.html.erb
<h1>Decks</h1>

<%= link_to "New deck", new_deck_path %>

<% @decks.each do |deck| %>
  <div>
    <%= link_to deck.name, deck %>
    -
    <%= link_to "Edit", edit_deck_path(deck) %>
    <%= link_to "Delete", deck, method: :delete, confirm: "Are you sure?" %>
  </div>
<% end %>

flashme/app/views/decks/new.html.erb
New Deck
<%= form_for(@deck) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "New deck" %>
<% end %>

flashme/app/views/decks/show.html.erb
<%= @deck.name %>

<%= link_to "Add card", new_deck_card_path(@deck) %>

<% @cards.each do |card| %>
  <div>
    <%= link_to card.front, [@deck, card] %>
    -
    <%= link_to "Edit", edit_deck_card_path(@deck, card) %>
    <%= link_to "Delete", [@deck, card], method: :delete, confirm: "Are you sure?" %>
  </div>
<% end %>

flashme/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if signed_in? %>
    Welcome <%= current_user.username %>
    <%= link_to "Sign out", session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_session_path %>
    <%= link_to "Sign up", new_user_path %>
  <% end %>

<%= yield %>

</body>
</html>

flashme/app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <%= form.submit "Sign up" %>
<% end %>

flashme/app/views/welcome/show.html.erb
Welcome